{
  "formatVersion": "1.1",
  "component": {
    "group": "su.kore",
    "module": "pluck",
    "version": "1.0.0-RC2-krd",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "pluck-1.0.0-RC2-krd.aar",
          "url": "pluck-1.0.0-RC2-krd.aar",
          "size": 85671,
          "sha512": "1841774d40e531025a0df78bbc5e5d303489e411e2147679fd4dc2b6f1a1766c1d600d0af721a984253e2230fac5ebdee4353db017868dd3040bca9ac6429200",
          "sha256": "3bba425fb5ce5eadfc87df608ca04b778c10c4180a8b7ba0b3f7882675f067f5",
          "sha1": "349c7ad7a7ea7d27e77400b8f2f6af77fa65738e",
          "md5": "0a21f90fad4c222a6c0f6daec2a97bc0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.24.1-alpha"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pluck-1.0.0-RC2-krd.aar",
          "url": "pluck-1.0.0-RC2-krd.aar",
          "size": 85671,
          "sha512": "1841774d40e531025a0df78bbc5e5d303489e411e2147679fd4dc2b6f1a1766c1d600d0af721a984253e2230fac5ebdee4353db017868dd3040bca9ac6429200",
          "sha256": "3bba425fb5ce5eadfc87df608ca04b778c10c4180a8b7ba0b3f7882675f067f5",
          "sha1": "349c7ad7a7ea7d27e77400b8f2f6af77fa65738e",
          "md5": "0a21f90fad4c222a6c0f6daec2a97bc0"
        }
      ]
    }
  ]
}
